<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXAxO1gH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXAxO1gH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXAxO1gH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXAxO1gH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXAxO1gH\App_KernelDevDebugContainer([
    'container.build_hash' => 'XAxO1gH',
    'container.build_id' => '0d8d669c',
    'container.build_time' => 1651580732,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXAxO1gH');
